import { useState } from "react";
import {v4 as uuidv4} from "uuid";

export default function TodoList(){
    let[todos, setTodos ] = useState([{task : "Sample-tasks", id: uuidv4(), isDone : false}]);      // isdone will show use is that task is done or not
    let[newTodo, setNewTodo] = useState("");

    let addNewTask = () => {
        setTodos((prevTodos) => {
        return [...todos, {task : newTodo, id : uuidv4(), isDone : false }]
    });
        setNewTodo("");
    };

    let updateTodoValue = (event) => { 
        setNewTodo(event.target.value);
    }; 

    let deleteTodo = (id) =>{                   // for delete data from array in react fix method is filter
        setTodos((prevTodos) => todos.filter((prevTodos) => prevTodos.id != id));
    };

    let markAllDone = () => {                   // changes in array all data
        setTodos( (prevTodos ) =>(
            prevTodos.map((todo) => {           // we will use map method to changes in all array
                return{
                    ...todo,                    // old data
                    isDone : true,              // changes in old data and set isDone to true for all array data 
                };
            })
        ));
    };


    let markAsDone = (id) => {                  // changes in array single data use its id ( generated by uuidv4 => npm ) 
        setTodos(( todos ) => 
            prevTasks.map((todo) => {
                if(todo.id === id) {
                    return {
                        ...todo,                // old data
                        isDone: true,           // changes in old data and set isDone to true for sigle array data using its id
                    };
                }else{
                    return todo;
                }
            })
        );
    };

    return(
        <div>
            <input placeholder="add a task" value = { newTodo } onChange={ updateTodoValue } ></input>
            <button onClick = { addNewTask } >Add task</button>
            <br></br> 
            <br></br>
            <br></br>
            <br></br>

            <hr></hr>
            <h4> Task Todo </h4>
            <ul>
                { todos.map((todo)=>(                   // for render data from array in react fix method is map function
                    <li key = {todo.id}> 
                    <span style = {todo.isDone ? { textDecorationLine : "line-through" } : {} } > {todo.task}</span>        if is done is true then line cross that array data else not
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <button onClick={()=>deleteTodo(todo.id)}>Delete</button>
                    <button onClick={()=>markAsDone(todo.id)}>mark As Done </button>
                    </li>
                ))}
            </ul>
            <br></br>
            <button onClick = { markAllDone }>markAllDone </button>
        </div>
    )
}